/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as QuickStartRouteImport } from './routes/quick-start'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PostAdIndexRouteImport } from './routes/post-ad/index'
import { Route as HotelsIndexRouteImport } from './routes/hotels/index'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ConversationsIndexRouteImport } from './routes/conversations/index'
import { Route as CompaniesIndexRouteImport } from './routes/companies/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as ProfileHotelContentsRouteImport } from './routes/profile/hotel-contents'
import { Route as ProfileHotelRouteImport } from './routes/profile/hotel'
import { Route as ConversationsIdRouteImport } from './routes/conversations/$id'
import { Route as AuthRegisterCompanyRouteImport } from './routes/auth.register-company'
import { Route as AuthPendingApprovalRouteImport } from './routes/auth.pending-approval'
import { Route as AdIdRouteImport } from './routes/ad/$id'
import { Route as HotelsIdIndexRouteImport } from './routes/hotels/$id/index'
import { Route as HotelsIdContentsContentIdRouteImport } from './routes/hotels/$id/contents/$contentId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickStartRoute = QuickStartRouteImport.update({
  id: '/quick-start',
  path: '/quick-start',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAdIndexRoute = PostAdIndexRouteImport.update({
  id: '/post-ad/',
  path: '/post-ad/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIndexRoute = HotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIndexRoute = ConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHotelContentsRoute = ProfileHotelContentsRouteImport.update({
  id: '/profile/hotel-contents',
  path: '/profile/hotel-contents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHotelRoute = ProfileHotelRouteImport.update({
  id: '/profile/hotel',
  path: '/profile/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsIdRoute = ConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterCompanyRoute = AuthRegisterCompanyRouteImport.update({
  id: '/auth/register-company',
  path: '/auth/register-company',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPendingApprovalRoute = AuthPendingApprovalRouteImport.update({
  id: '/auth/pending-approval',
  path: '/auth/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdIdRoute = AdIdRouteImport.update({
  id: '/ad/$id',
  path: '/ad/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIdIndexRoute = HotelsIdIndexRouteImport.update({
  id: '/hotels/$id/',
  path: '/hotels/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelsIdContentsContentIdRoute =
  HotelsIdContentsContentIdRouteImport.update({
    id: '/hotels/$id/contents/$contentId',
    path: '/hotels/$id/contents/$contentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/quick-start': typeof QuickStartRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/ad/$id': typeof AdIdRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/register-company': typeof AuthRegisterCompanyRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/profile/hotel': typeof ProfileHotelRoute
  '/profile/hotel-contents': typeof ProfileHotelContentsRoute
  '/auth/': typeof AuthIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/post-ad/': typeof PostAdIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/hotels/$id/': typeof HotelsIdIndexRoute
  '/hotels/$id/contents/$contentId': typeof HotelsIdContentsContentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/quick-start': typeof QuickStartRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/ad/$id': typeof AdIdRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/register-company': typeof AuthRegisterCompanyRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/profile/hotel': typeof ProfileHotelRoute
  '/profile/hotel-contents': typeof ProfileHotelContentsRoute
  '/auth': typeof AuthIndexRoute
  '/companies': typeof CompaniesIndexRoute
  '/conversations': typeof ConversationsIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/hotels': typeof HotelsIndexRoute
  '/post-ad': typeof PostAdIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/hotels/$id': typeof HotelsIdIndexRoute
  '/hotels/$id/contents/$contentId': typeof HotelsIdContentsContentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/quick-start': typeof QuickStartRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/ad/$id': typeof AdIdRoute
  '/auth/pending-approval': typeof AuthPendingApprovalRoute
  '/auth/register-company': typeof AuthRegisterCompanyRoute
  '/conversations/$id': typeof ConversationsIdRoute
  '/profile/hotel': typeof ProfileHotelRoute
  '/profile/hotel-contents': typeof ProfileHotelContentsRoute
  '/auth/': typeof AuthIndexRoute
  '/companies/': typeof CompaniesIndexRoute
  '/conversations/': typeof ConversationsIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/hotels/': typeof HotelsIndexRoute
  '/post-ad/': typeof PostAdIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/hotels/$id/': typeof HotelsIdIndexRoute
  '/hotels/$id/contents/$contentId': typeof HotelsIdContentsContentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/home'
    | '/notifications'
    | '/privacy'
    | '/quick-start'
    | '/terms'
    | '/verify'
    | '/ad/$id'
    | '/auth/pending-approval'
    | '/auth/register-company'
    | '/conversations/$id'
    | '/profile/hotel'
    | '/profile/hotel-contents'
    | '/auth/'
    | '/companies/'
    | '/conversations/'
    | '/explore/'
    | '/hotels/'
    | '/post-ad/'
    | '/profile/'
    | '/hotels/$id/'
    | '/hotels/$id/contents/$contentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/home'
    | '/notifications'
    | '/privacy'
    | '/quick-start'
    | '/terms'
    | '/verify'
    | '/ad/$id'
    | '/auth/pending-approval'
    | '/auth/register-company'
    | '/conversations/$id'
    | '/profile/hotel'
    | '/profile/hotel-contents'
    | '/auth'
    | '/companies'
    | '/conversations'
    | '/explore'
    | '/hotels'
    | '/post-ad'
    | '/profile'
    | '/hotels/$id'
    | '/hotels/$id/contents/$contentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/faq'
    | '/home'
    | '/notifications'
    | '/privacy'
    | '/quick-start'
    | '/terms'
    | '/verify'
    | '/ad/$id'
    | '/auth/pending-approval'
    | '/auth/register-company'
    | '/conversations/$id'
    | '/profile/hotel'
    | '/profile/hotel-contents'
    | '/auth/'
    | '/companies/'
    | '/conversations/'
    | '/explore/'
    | '/hotels/'
    | '/post-ad/'
    | '/profile/'
    | '/hotels/$id/'
    | '/hotels/$id/contents/$contentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  QuickStartRoute: typeof QuickStartRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  AdIdRoute: typeof AdIdRoute
  AuthPendingApprovalRoute: typeof AuthPendingApprovalRoute
  AuthRegisterCompanyRoute: typeof AuthRegisterCompanyRoute
  ConversationsIdRoute: typeof ConversationsIdRoute
  ProfileHotelRoute: typeof ProfileHotelRoute
  ProfileHotelContentsRoute: typeof ProfileHotelContentsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
  ConversationsIndexRoute: typeof ConversationsIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  HotelsIndexRoute: typeof HotelsIndexRoute
  PostAdIndexRoute: typeof PostAdIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  HotelsIdIndexRoute: typeof HotelsIdIndexRoute
  HotelsIdContentsContentIdRoute: typeof HotelsIdContentsContentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-start': {
      id: '/quick-start'
      path: '/quick-start'
      fullPath: '/quick-start'
      preLoaderRoute: typeof QuickStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ad/': {
      id: '/post-ad/'
      path: '/post-ad'
      fullPath: '/post-ad/'
      preLoaderRoute: typeof PostAdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/': {
      id: '/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof HotelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/': {
      id: '/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/hotel-contents': {
      id: '/profile/hotel-contents'
      path: '/profile/hotel-contents'
      fullPath: '/profile/hotel-contents'
      preLoaderRoute: typeof ProfileHotelContentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/hotel': {
      id: '/profile/hotel'
      path: '/profile/hotel'
      fullPath: '/profile/hotel'
      preLoaderRoute: typeof ProfileHotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations/$id': {
      id: '/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/conversations/$id'
      preLoaderRoute: typeof ConversationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-company': {
      id: '/auth/register-company'
      path: '/auth/register-company'
      fullPath: '/auth/register-company'
      preLoaderRoute: typeof AuthRegisterCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pending-approval': {
      id: '/auth/pending-approval'
      path: '/auth/pending-approval'
      fullPath: '/auth/pending-approval'
      preLoaderRoute: typeof AuthPendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad/$id': {
      id: '/ad/$id'
      path: '/ad/$id'
      fullPath: '/ad/$id'
      preLoaderRoute: typeof AdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$id/': {
      id: '/hotels/$id/'
      path: '/hotels/$id'
      fullPath: '/hotels/$id/'
      preLoaderRoute: typeof HotelsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotels/$id/contents/$contentId': {
      id: '/hotels/$id/contents/$contentId'
      path: '/hotels/$id/contents/$contentId'
      fullPath: '/hotels/$id/contents/$contentId'
      preLoaderRoute: typeof HotelsIdContentsContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  QuickStartRoute: QuickStartRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  AdIdRoute: AdIdRoute,
  AuthPendingApprovalRoute: AuthPendingApprovalRoute,
  AuthRegisterCompanyRoute: AuthRegisterCompanyRoute,
  ConversationsIdRoute: ConversationsIdRoute,
  ProfileHotelRoute: ProfileHotelRoute,
  ProfileHotelContentsRoute: ProfileHotelContentsRoute,
  AuthIndexRoute: AuthIndexRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
  ConversationsIndexRoute: ConversationsIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  HotelsIndexRoute: HotelsIndexRoute,
  PostAdIndexRoute: PostAdIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  HotelsIdIndexRoute: HotelsIdIndexRoute,
  HotelsIdContentsContentIdRoute: HotelsIdContentsContentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
