import api from '@/lib/api-client';
import { NotificationsResponse, UnreadCountResponse } from '../types';

export const notificationsService = {
  /**
   * Registers (or updates) the device FCM token on the backend.
   * Must be called every time a new token is generated by the native FCM SDK
   * or the Firebase Web SDK. The server uses this token to send push notifications.
   *
   * @param token   - The FCM registration token (native device token or VAPID web token)
   * @param platform - 'android' | 'ios' | 'web'
   */
  registerDevice: async (token: string, platform: string): Promise<{ status: boolean; message: string }> => {
    return api.post<{ status: boolean; message: string }>('/notifications/register-device', {
      token,
      platform,
    });
  },

  /**
   * Fetch all notifications with pagination
   */
  getNotifications: async (page: number = 1): Promise<NotificationsResponse> => {
    return api.get<NotificationsResponse>('/notifications', { query: { page } });
  },

  /**
   * Get unread notifications count
   */
  getUnreadCount: async (): Promise<UnreadCountResponse> => {
    return api.get<UnreadCountResponse>('/notifications/unread');
  },

  /**
   * Delete a specific notification by ID
   */
  deleteNotification: async (id: string): Promise<{ status: boolean; message: string }> => {
    return api.delete<{ status: boolean; message: string }>(`/notifications/${id}`);
  },

  /**
   * Delete all notifications
   */
  deleteAllNotifications: async (): Promise<{ status: boolean; message: string }> => {
    return api.delete<{ status: boolean; message: string }>('/notifications');
  },
};
